@echo off
echo 📦 Compiling fresh web build...
call npm run build

echo 🔄 Syncing local Capacitor files...
call npm exec cap sync android

echo 📂 Moving into Android directory...
cd android

echo ⚙️ Setting Android SDK Path...
set ANDROID_HOME=C:\Users\Shawn\Downloads\AndroidSDK

echo 🔨 Building the APK (This might take a minute)...
call gradlew assembleDebug

echo ✅ Build Complete! Opening your APK folder...
explorer "C:\Users\Shawn\Documents\OPEN MART APP\openmart-production-v2\openmart-production\android\app\build\outputs\apk\debug"

echo 🔙 Returning to main project folder...
cd ..